# https://taskfile.dev

version: '3'

dotenv: ['.env']

vars:
  output: dist
  # date: '{{now | date "2006-01-02 15:04:05"}}'
  version:
    sh: git tag -l --points-at HEAD
  args:
    -trimpath
    --ldflags="-w -s -X main.Version={{.version}}"
    -o {{.output}}

tasks:
  default:
    cmds:
      - go run . -name tomose_shunsaku
  
  build:
    - rm -rf {{.output}}
    - mkdir -p {{.output}}
    - go build -o {{.output}} .

  release:
    cmds:
      - rm -rf {{.output}}
      - mkdir -p {{.output}}
      - |
        {{range list "linux" "windows"}}
        GOOS={{.}} go build {{$.args}} .
        {{- end}}

  tidy:
    cmds:
      - go mod tidy
